
try{
    console.log("before in try block")
    var x=10*y;
    console.log(x);
}catch(err){
    console.log("before in catch block")
    console.log("Error Occured");
    console.log("After in try block")
}